# Generated by Django 3.2.20 on 2023-08-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20230804_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='', max_length=300, unique=True),
        ),
    ]
