# Generated by Django 3.2.20 on 2023-08-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(editable=False, max_length=32)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(choices=[('Microneedling', 'Microneedling'), ('Facial', 'Facial'), ('Chemical Peel', 'Chemical Peel'), ('Microdermabrasion', 'Microdermabrasion'), ('Botox', 'Botox'), ('Derma Fillers', 'Derma Fillers'), ('Laser treatments', 'Laser treatments'), ('IPL (Intense Pulsed Light)', 'IPL (Intense Pulsed Light)')], default=('Microneedling', 'Microneedling'), max_length=50)),
                ('package', models.CharField(choices=[('Package Bronze', 'Package Bronze'), ('Package Silver', 'Package Silver'), ('Package Gold', 'Package Gold')], default=('Package Bronze', 'Package Bronze'), max_length=50)),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('10.00 - 11.00', '10.00 - 11.00'), ('11.00 - 12.00', '11.00 - 12.00'), ('12.00 - 13.00', '12.00 - 13.00'), ('13.00 - 14.00', '13.00 - 14.00'), ('14.00 - 15.00', '14.00 - 15.00'), ('15.00 - 16.00', '15.00 - 16.00'), ('16.00 - 17.00', '16.00 - 17.00'), ('17.00 - 18.00', '17.00 - 18.00')], default=('10.00 - 11.00', '10.00 - 11.00'), max_length=15)),
            ],
        ),
    ]
