# Generated by Django 3.2.20 on 2023-08-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
