# Generated by Django 3.2.20 on 2023-08-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.CharField(choices=[('Package Bronze', 'Package Bronze'), ('Package Silver', 'Package Silver'), ('Package Gold', 'Package Gold')], max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('Microneedling', 'Microneedling'), ('Facial', 'Facial'), ('Chemical Peel', 'Chemical Peel'), ('Microdermabrasion', 'Microdermabrasion'), ('Botox', 'Botox'), ('Derma Fillers', 'Derma Fillers'), ('Laser treatments', 'Laser treatments'), ('IPL (Intense Pulsed Light)', 'IPL (Intense Pulsed Light)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Canceled')], default=(0, 'Pending'), max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('10.00 - 11.00', '10.00 - 11.00'), ('11.00 - 12.00', '11.00 - 12.00'), ('12.00 - 13.00', '12.00 - 13.00'), ('13.00 - 14.00', '13.00 - 14.00'), ('14.00 - 15.00', '14.00 - 15.00'), ('15.00 - 16.00', '15.00 - 16.00'), ('16.00 - 17.00', '16.00 - 17.00'), ('17.00 - 18.00', '17.00 - 18.00')], max_length=15),
        ),
    ]
